import datetime 
params ={   'cancelinvoices': '/api/cancelinvoice.json',
    'clients': '/api/clients.json',
    'errors': '/api/logs.json',
    'init': 1,
    'interval': '1800',
    'invoices': '/api/invoices.json',
    'log_error_file': 'errors.log',
    'log_file': 'loader.log',
    'log_size': 2,
    'login': '/api/login.json',
    'no_id': ['01'],
    'owners': '/api/owners.json',
    'port': '8000',
    'products': '/api/products.json',
    'stopper' : 1,
    'time_init': datetime.datetime(2014, 3, 31, 12, 31, 45, 643632),
    'time_load': datetime.datetime(2014, 3, 31, 12, 29, 0, 250172),
    'url': 'http://190.9.43.239'}
