import datetime 
params ={   'cancelinvoices': '/api/cancelinvoice.json',
    'clients': '/api/clients.json',
    'errors': '/api/logs.json',
    'init': 1,
    'interval': '1800',
    'invoices': '/api/invoices.json',
    'last_folder': 20140618,
    'log_error_file': 'errors.log',
    'log_file': 'loader.log',
    'log_size': 2,
    'login': '/api/login.json',
    'owners': '/api/owners.json',
    'port': '80',
    'products': '/api/products.json',
    'stopper': 0,
    'tax': 0.12,
    'time_init': datetime.datetime(2014, 4, 2, 9, 35, 3, 262496),
    'time_load': datetime.datetime(2014, 4, 2, 9, 35, 3, 262496),
    'url': 'http://xdata.lealtag.com'}
